### ISSUE TITLE
Publish GH Action to deploy `upgrade-provider`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/upgrade-provider#12]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Reduce the steps needed for a user to use this tool in their own repository. For example, to run it on a cron via GitHub Actions:

```yaml
on:
 schedule: ... # cron job

jobs:
  upgrade-provider:
    steps:
    - name: Run upgrade provider
      uses: pulumi/upgrade-provider@v2 # for example 
```
