### ISSUE TITLE
GCP upgrade failing

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#155]
### What happened?

GCP upgrade failed with the following error:

```
../upstream/go.mod: open /home/runner/work/pulumi-gcp/pulumi-gcp/upstream/go.mod: no such file or directory
```

https://github.com/pulumi/pulumi-gcp/actions/runs/6224216436/job/16891916772#step:3:1446

The workflow definition is just this:

```
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@v0.0.6
      with:
        kind: all
```

And pulumi/pulumi-upgrade-provider-action installs upgrade-provider floating version at main branch.

github.com/pulumi/upgrade-provider v0.0.0-20230915232329-b8901aa1bf6b is the version that got picked.

The job attempts a --kind all upgrade.

Locally I seem to succeed performing the following GCP update:

- pulumi-gcp at ddeea7823ef1d5b1346454840312052e6178f347
- upgrade-provider at b8901aa1bf6bcea8005ea2a0614fee1407aa00d1
- ~/code/upgrade-provider/upgrade-provider pulumi/pulumi-gcp --kind provider

This takes a while but succeeds.

I wonder what is the difference between upstream handling in local vs CI?

### Example

See above

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
