### ISSUE TITLE
Automate updating pinned external provider references

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#263]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

To stabilize provider builds we currently pin external provider references so that examples that use an external provider (i.e. `aws` provider when building a provider other than `aws` such as `awsx`) render in a stable manner. However issues remain when these references remain stale. Examples drop out or render inaccurately.

How are these pinned? See .ci-mgmt.yaml in pulumi-aws for a good recent example, it has a section:

```
plugins:
  - name: archive
    version: "0.0.1"
  - name: tls
    version: "4.10.0"
  - name: github
    version: "4.10.0"
  - name: kubernetes
    version: "4.11.0"
  - name: "null"
    version: "0.0.3"
  - name: "local"
    version: "0.1.0"
  - name: random
    version: "4.8.2"
  - name: github
    version: "5.14.0"
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.17"
    kind: converter

```

Suggest automating this:

- read plugins
- for each plugin find the latest version on Pulumi
- if below latest version, edit it
- stop after first plugin
- make tfgen
- check in the code and create a PR
