### ISSUE TITLE
Provide a composite action for running upgrade provider

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/upgrade-provider#43]
Reduce the steps needed for a user to use this tool in their own repository to, e.g.:

```yaml
on:
 schedule: ... # cron job

jobs:
  upgrade-provider:
    steps:
    - name: Run upgrade provider
      uses: pulumi/upgrade-provider@v2 # for example 
```
